### ISSUE TITLE
Refactor StockDataFetcherApp to Integrate with DataIOButler for Redis Interactions

### ISSUE THREAD

**Issue by PenHsuanWang** [PenHsuanWang/stock-analyzer-backend#5]
With the recent development of the `DataIOButler` class, which provides an encapsulated way to interact with our Redis instance for stock data management, it's necessary to refactor the existing `StockDataFetcherApp` to leverage this utility. By doing so, we can make the data-fetching and data-management processes more consistent, efficient, and maintainable.

**Tasks**:
- [ ] Replace direct Redis client instantiation in `StockDataFetcherApp` with an instance of `DataIOButler`.
- [ ] Refactor `fetch_data_and_stash` method in `StockDataFetcherApp` to use the data stashing functionalities provided by `DataIOButler`.
- [ ] Update any other relevant code that directly interacts with Redis to use `DataIOButler` instead.
- [ ] Ensure all tests pass and there are no regressions.

**Additional Information**:
- The goal is to ensure that Redis interactions are consistent and managed in one place (`DataIOButler`). This will ease future enhancements and debugging.
- While refactoring, ensure that error handling remains consistent and errors are appropriately propagated to the calling functions or APIs.

**Reference Files**:
- `webapp/data_fetcher_serving_app.py`
- `src/manager/data_manager.py`

Current Implementation in `StockDataFetcherApp`:
```python
self._redis_client = redis.StrictRedis(host='localhost', port=6379, db=0)  # adjust as necessary

def fetch_data_and_stash(self, stock_id: str, start_date: str, end_date: str) -> None:
    df = self.fetch_data_and_get_as_dataframe(stock_id, start_date, end_date)
    key = f"stock_data:{stock_id}:{start_date}:{end_date}"
    # Convert DataFrame to JSON and store it in Redis
    self._redis_client.set(key, df.to_json(orient="records"))

```

Expected Integration with `DataIOButler`:
```python
data_io_butler = DataIOButler()

def fetch_data_and_stash(self, stock_id: str, start_date: str, end_date: str) -> None:
    df = self.fetch_data_and_get_as_dataframe(stock_id, start_date, end_date)
    data_io_butler.update_data(stock_id, start_date, end_date, df)
```
